services:
  - type: web
    name: mineka-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_CREDENTIALS_PATH
        sync: false
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false
      - key: GOOGLE_SPREADSHEET_ID
        sync: false
      - key: PORT
        value: 10000

